Beginning trial 2 of 3
Gathering sys log on node001
:::MLL 1586878679.028 submission_benchmark: {"value": "ssd", "metadata": {"file": "mlperf_log_utils.py", "lineno": 176}}
:::MLL 1586878679.029 submission_org: {"value": "NVIDIA", "metadata": {"file": "mlperf_log_utils.py", "lineno": 181}}
WARNING: Log validation: Key "submission_division" is not in known ssd keys.
:::MLL 1586878679.030 submission_division: {"value": "closed", "metadata": {"file": "mlperf_log_utils.py", "lineno": 185}}
:::MLL 1586878679.031 submission_status: {"value": "onprem", "metadata": {"file": "mlperf_log_utils.py", "lineno": 189}}
:::MLL 1586878679.031 submission_platform: {"value": "1xPowerEdge R7525", "metadata": {"file": "mlperf_log_utils.py", "lineno": 193}}
:::MLL 1586878679.032 submission_entry: {"value": "{'hardware': 'PowerEdge R7525', 'framework': 'PyTorch NVIDIA Release 19.05', 'power': 'N/A', 'notes': 'N/A', 'interconnect': ' ', 'os': '\\\\S / ', 'libraries': \"{'container_base': 'Ubuntu-16.04', 'openmpi_version': '3.1.3', 'mofed_version': '4.0-0', 'cuda_version': '10.1.163', 'cuda_driver_version': '418.67', 'nccl_version': '2.4.6', 'cudnn_version': '7.6.0.64', 'cublas_version': '10.2.0.163', 'trt_version': '5.1.5.0', 'dali_version': '0.9.1'}\", 'compilers': 'gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609', 'nodes': \"{'num_nodes': '1', 'cpu': '2x AMD EPYC 7502 32-Core Processor', 'num_cores': '64', 'num_vcpus': '64', 'accelerator': 'Tesla V100S-PCIE-32GB', 'num_accelerators': '3', 'sys_mem_size': '251 GB', 'sys_storage_type': 'NVMe SSD', 'sys_storage_size': '1x 931.5G', 'cpu_accel_interconnect': 'QPI', 'network_card': '', 'num_network_cards': '0', 'notes': ''}\"}", "metadata": {"file": "mlperf_log_utils.py", "lineno": 197}}
:::MLL 1586878679.033 submission_poc_name: {"value": "Paulius Micikevicius", "metadata": {"file": "mlperf_log_utils.py", "lineno": 201}}
:::MLL 1586878679.034 submission_poc_email: {"value": "pauliusm@nvidia.com", "metadata": {"file": "mlperf_log_utils.py", "lineno": 205}}
Clearing caches
:::MLL 1586878680.112 cache_clear: {"value": true, "metadata": {"file": "<string>", "lineno": 1}}
Launching on node node001
+ pids+=($!)
+ set +x
++ eval echo
+++ echo
+ docker exec -e DGXSYSTEM=DGX1 -e 'MULTI_NODE= --master_port=4529' -e SLURM_JOB_ID=200414103423859271850 -e SLURM_NTASKS_PER_NODE= cont_200414103423859271850 ./run_and_time.sh
Run vars: id 200414103423859271850 gpus 3 mparams  --master_port=4529
STARTING TIMING RUN AT 2020-04-14 03:38:00 PM
+ NUMEPOCHS=80
+ echo 'running benchmark'
running benchmark
+ export DATASET_DIR=/data/coco2017
+ DATASET_DIR=/data/coco2017
+ export TORCH_MODEL_ZOO=/data/torchvision
+ TORCH_MODEL_ZOO=/data/torchvision
+ python -m bind_launch --nsockets_per_node 2 --ncores_per_socket 32 --nproc_per_node 3 --master_port=4529 --no_hyperthreads --no_membind train.py --use-fp16 --nhwc --pad-input --jit --delay-allreduce --opt-loss --epochs 80 --warmup-factor 0 --no-save --threshold=0.23 --data /data/coco2017 --evaluation 120000 160000 180000 200000 220000 240000 260000 280000 --batch-size 256 --eval-batch-size 160 --warmup 650 --lr 2.92e-3 --wd 1.6e-4 --use-nvjpeg --use-roi-decode
:::MLL 1586878682.323 init_start: {"value": null, "metadata": {"file": "train.py", "lineno": 833}}
:::MLL 1586878682.323 init_start: {"value": null, "metadata": {"file": "train.py", "lineno": 833}}
:::MLL 1586878682.324 init_start: {"value": null, "metadata": {"file": "train.py", "lineno": 833}}
BN group: 1
BN group: 1
BN group: 1
2 Using seed = 3752289086
1 Using seed = 3752289085
0 Using seed = 3752289084
:::MLL 1586878687.841 max_samples: {"value": 1, "metadata": {"file": "utils.py", "lineno": 465}}
/opt/conda/lib/python3.6/site-packages/torch/nn/_reduction.py:46: UserWarning: size_average and reduce args will be deprecated, please use reduction='none' instead.
  warnings.warn(warning.format(ret))
Delaying allreduces to the end of backward()
:::MLL 1586878688.497 model_bn_span: {"value": 256, "metadata": {"file": "train.py", "lineno": 480}}
:::MLL 1586878688.497 global_batch_size: {"value": 768, "metadata": {"file": "train.py", "lineno": 481}}
:::MLL 1586878688.505 opt_base_learning_rate: {"value": 0.07, "metadata": {"file": "train.py", "lineno": 511}}
:::MLL 1586878688.505 opt_weight_decay: {"value": 0.00016, "metadata": {"file": "train.py", "lineno": 513}}
:::MLL 1586878688.505 opt_learning_rate_warmup_steps: {"value": 650, "metadata": {"file": "train.py", "lineno": 516}}
:::MLL 1586878688.505 opt_learning_rate_warmup_factor: {"value": 0, "metadata": {"file": "train.py", "lineno": 518}}
/opt/conda/lib/python3.6/site-packages/torch/nn/_reduction.py:46: UserWarning: size_average and reduce args will be deprecated, please use reduction='none' instead.
  warnings.warn(warning.format(ret))
/opt/conda/lib/python3.6/site-packages/torch/nn/_reduction.py:46: UserWarning: size_average and reduce args will be deprecated, please use reduction='none' instead.
  warnings.warn(warning.format(ret))
epoch nbatch loss
:::MLL 1586878695.196 init_stop: {"value": null, "metadata": {"file": "train.py", "lineno": 604}}
:::MLL 1586878695.197 run_start: {"value": null, "metadata": {"file": "train.py", "lineno": 610}}
loading annotations into memory...
loading annotations into memory...
loading annotations into memory...
Traceback (most recent call last):
  File "train.py", line 852, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
  File "train.py", line 852, in <module>
  File "train.py", line 852, in <module>
    main()
  File "train.py", line 844, in main
    main()
    main()
  File "train.py", line 844, in main
  File "train.py", line 844, in main
    success = train300_mlperf_coco(args)
  File "train.py", line 612, in train300_mlperf_coco
    success = train300_mlperf_coco(args)
    success = train300_mlperf_coco(args)
  File "train.py", line 612, in train300_mlperf_coco
  File "train.py", line 612, in train300_mlperf_coco
    cocoGt = COCO(annotation_file=val_annotate, use_ext=True)
  File "/opt/conda/lib/python3.6/site-packages/pycocotools/coco.py", line 85, in __init__
    cocoGt = COCO(annotation_file=val_annotate, use_ext=True)
    cocoGt = COCO(annotation_file=val_annotate, use_ext=True)
  File "/opt/conda/lib/python3.6/site-packages/pycocotools/coco.py", line 85, in __init__
  File "/opt/conda/lib/python3.6/site-packages/pycocotools/coco.py", line 85, in __init__
    dataset = json.load(open(annotation_file, 'r'))
    dataset = json.load(open(annotation_file, 'r'))
    dataset = json.load(open(annotation_file, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: '/data/coco2017/annotations/instances_val2017.json'
FileNotFoundError: [Errno 2] No such file or directory: '/data/coco2017/annotations/instances_val2017.json'
FileNotFoundError: [Errno 2] No such file or directory: '/data/coco2017/annotations/instances_val2017.json'
+ ret_code=0
+ set +x
ENDING TIMING RUN AT 2020-04-14 03:38:19 PM
RESULT,SINGLE_STAGE_DETECTOR,,19,nvidia,2020-04-14 03:38:00 PM
